In [1]:
import numpy as np
import torch

1) Numpy array:

a = np.array([1,2,3])

Create new torch Tensor b with data from a, when you change a - changes b

In [5]:
a = np.arange(1, 4)
a

array([1, 2, 3])

In [6]:
tensor_a = torch.from_numpy(a)
tensor_a

tensor([1, 2, 3])

Changing the first element in the np array 

In [7]:
a[0] = 100

In [8]:
tensor_a

tensor([100,   2,   3])

change in np array is reflected in the torch tensor. 


2) Calculate std in PyTorch with results like in numpy (Hint: think about Bessel's correction )

In [9]:
x = torch.arange(10000).float()
numpy_std = x.numpy().std()
numpy_std

2886.7512

In [10]:
x.std()

tensor(2886.8958)

3) There are 2 matrix x,y: perform a matrix multiplication (Try different approaches)

In [23]:
x = torch.tensor([[1,2],
                  [3,4]])
y = torch.tensor([[5,6],
                  [7,8]])
xy = torch.matmul(x, y)

assert np.allclose(xy,np.dot(x.numpy(),y.numpy())),"Not the same!"
xy

tensor([[19, 22],
        [43, 50]])